project_id = "osmpjferqfgbfasstehg"

[functions.create-checkout-session]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.sync-stripe-product]
verify_jwt = false

[functions.get-stripe-price]
verify_jwt = false
